version: '3.8'

services:
  db:
    image: postgres:14.2-alpine
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    restart: always
    environment:
      POSTGRES_USER: kong_takehome
      POSTGRES_PASSWORD: abc123
    ports:
      - "8081:5432"
  web:
    build: .
    environment:
      DB_PASSWORD: abc123
    ports:
      - "8080:8080"
